version: "3"
services:
  db:
    image: "mongo"
    container_name: "photog-db"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$DB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$DB_PASS
    ports:
      - "27017:27017"
    volumes:
      - photog-data:/data/db/
  web:
    build: .
    volumes:
      - .:/app/
    environment:
      - NODE_PATH=/install/node_modules
    ports:
      - "3000:3000"
    command: npm start
    working_dir: /app/
volumes:
  photog-data:
    external:
      true
